
export const red = ['CREATE_INSTANT_INVITE', 'KICK_MEMBERS', 'BAN_MEMBERS', 'ADMINISTRATOR', 'MANAGE_CHANNEL', 'MANAGE_SERVER', 'MANAGE_ROLES', 'MANAGE_PERMISSIONS', 'MESSAGE_MENTION_EVERYONE', 'MESSAGE_TTS']
export const blue = ['VOICE_MOVE_OTHERS', 'NICKNAME_MANAGE', 'VOICE_DEAF_OTHERS', 'VOICE_MUTE_OTHERS', 'VIEW_GUILD_INSIGHTS', 'VIEW_AUDIT_LOGS']
export const green = ['VOICE_CONNECT', 'VOICE_SPEAK', 'NICKNAME_CHANGE', 'MESSAGE_EXT_EMOJI']
export const purple = ['MESSAGE_READ', 'MESSAGE_WRITE', 'MESSAGE_EMBED_LINKS', 'MESSAGE_ATTACH_FILES', 'MESSAGE_HISTORY', 'MESSAGE_EXT_EMOJI', 'VIEW_CHANNEL', 'MESSAGE_ADD_REACTION']
